In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("../data/raw/Chocolate Sales.csv")

In [6]:
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [7]:
New_Df=df.copy()

In [8]:
New_Df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 154.0 KB

In [9]:
New_Df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [10]:
New_Df['Date']=pd.to_datetime(New_Df['Date'],dayfirst=True)

In [11]:
New_Df['Amount']=(
                    New_Df['Amount']
                    .str.replace(',','')
                    .str.replace('$', '')
                    .astype(float)
)

In [12]:
New_Df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 154.0 KB

In [13]:
New_Df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [14]:
New_Df.to_csv("../data/processed/Chocolate_Limpo.csv", index=False)

In [15]:
Teste_df=New_Df.copy()

In [16]:
Teste_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 154.0 KB

In [17]:
Teste_df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [18]:
Teste2=df.copy()

In [19]:
Teste2.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [20]:
Teste2['Amount']=(
                    Teste2['Amount']
                    .str.replace(',','')
                    .str.replace('$', '')
                    .astype(float)

)

In [21]:
Teste2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: float64(1), int64(1), str(4)
memory usage: 154.0 KB

In [22]:
df2=pd.read_csv("../data/processed/Chocolate_Sales_final.csv")

In [23]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           1290 non-null   str
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: float64(1), int64(1), str(4)
memory usage: 154.0 KB

In [24]:
df2.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-04-01,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-01-08,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,NaN,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,NaN,13685.0,184